Gauge.xcodeproj/project.pbxproj
Gauge.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Gauge/Common/Models/Firebase.swift
Gauge/Common/Models/User.swift
Gauge/Common/ViewModels/AuthenticationVM.swift
Gauge/Common/ViewModels/FirebaseDemoVM.swift
Gauge/Common/ViewModels/FirebaseInitVM.swift
Gauge/Feed/Models/BinaryPost.swift
Gauge/Feed/Models/Post.swift
Gauge/Feed/Models/RankPost.swift
Gauge/Feed/Models/SliderPost.swift
Gauge/Feed/ViewModels/PostFirebase.swift
Gauge/Feed/ViewModels/UserFirebase.swift

Updated User + Post models, created template Firebase VMs for devs, Made Firebase Singleton

Initial work

---

Gauge/Profiles+Search/FriendsView.swift

Created FriendsView where users can search friends, view incoming/outgoing requests, and see their connections. Basic structure that developers will follow to implement

FriendsView

---

Gauge/Feed/ViewModels/PostFirebase.swift

added functions for adding comments and deleting comments

Feed hawthorne2

---

Gauge/Common/ViewModels/FirebaseDemoVM.swift
Gauge/Common/Views/DemoView.swift
Gauge/Feed/ViewModels/UserFirebase.swift

Create a function called func updateUserFields(user: User){} where update the userFields. 
Meanwhile also updating the firebasedemovm file with the example showcase for usage.
Added a button in the demoView for seeing the update in the backend firebase

Adding UpdateUserFields Method in the userFireBase and demo method

---

Gauge/Feed/ViewModels/UserFirebase.swift

function to see users responses, comments, and views

function to get users reponses, views, and comments

---

Gauge/Profiles+Search/ViewModels/FriendsViewModel.swift
GaugeTests/GaugeTests.swift

accepting and rejecting friend methods implemented

Add delete friend

---

Gauge/Games/TakeMatch/MultipeerConnectivity/MCManager.swift
Gauge/Games/TakeMatch/Views/TakeMatchHome.swift
Gauge/Games/TakeMatch/Views/TakeMatchRoomView.swift

Revert "Implemented a better multipeer connectivity. Users can join the same …"

---

Gauge/Feed/Models/Post.swift
Gauge/Feed/ViewModels/PostFirebase.swift

Add the function getComments
- It will return an array of element, each index contain one comment with its fields. 
- since the profile photo and user id will not stored in the comment field in firebase, the default value set to "" empty string.
- modified the CommentType where each of the case is a String stored in the firebase as listed.

Add funcion getComments for all comment from a post Id

---

Gauge/Feed/ViewModels/PostFirebase.swift

Wrote func getNextFeedPost() function and set up Listeners for each of the subcollection of the first feed post.

Feed shreeya

---

Gauge/Feed/ViewModels/PostFirebase.swift

date converter

---

Gauge/Feed/ViewModels/UserFirebase.swift
Gauge/Feed/Views/FirebaseTesting.swift

I have reset a new branch for it since i don't know how to delete the certain commit in xcode, now it should have the 2 files changed only!

Commit the Reordering category without extra cache files

---

Gauge/Common/Models/User.swift
Gauge/Feed/ViewModels/UserFirebase.swift

- updated the userFirebase.swift file
- update the constructor of the User file
- added another field called myProfileSearches
- changed mySearches to myPostSearches

refactor the user searches

---

Gauge/Common/Models/User.swift
Gauge/Common/Views/ContentView.swift
Gauge/Feed/ViewModels/PostFirebase.swift
Gauge/Feed/ViewModels/UserFirebase.swift
Gauge/Feed/Views/FeedView.swift
Gauge/Feed/Views/FirebaseTesting.swift
Gauge/Profiles+Search/ViewModels/FriendsViewModel.swift

Making closure functions async, getting all user data from Firebase on launch, fully integrating skip post & selection algo

Lots of Firebase integration for Feed

---

Gauge/Feed/ViewModels/PostFirebase.swift
Gauge/Feed/Views/FeedView.swift

fixed merge issues with last PR

Functionality for Adding Responses and Views to Firebase

---

Gauge/Feed/Views/SelectLabelNames.swift

for testing the button, uncommon this these line:
//            if let option = selectedOption {
//                Text("You chose: \(option)")
//                    .foregroundColor(.black)
//            }

adding the sliding post for selected label view

---

Gauge/Common/Models/User.swift
Gauge/Feed/ViewModels/PostFirebase.swift
Gauge/Feed/ViewModels/UserFirebase.swift

Reorder user's topics base on most interacted with

Created reorderUserTopics() function

---

Gauge/Common/Models/User.swift
Gauge/Common/ViewModels/AuthenticationVM.swift
Gauge/Feed/Models/BinaryPost.swift
Gauge/Feed/Models/Post.swift
Gauge/Feed/Models/RankPost.swift
Gauge/Feed/Models/SliderPost.swift
Gauge/Feed/ViewModels/PostFirebase.swift
Gauge/Feed/ViewModels/UserFirebase.swift
Gauge/Feed/Views/BinaryFeedPost.swift
Gauge/Feed/Views/BinaryFeedResults.swift
Gauge/Feed/Views/BinaryResultView.swift
Gauge/Feed/Views/FeedView.swift
Gauge/Feed/Views/FirebaseTesting.swift
Gauge/Profiles+Search/ViewModels/FriendsViewModel.swift

Feed austin

---

Gauge/Feed/Views/AddCommentView.swift
Gauge/Feed/Views/HomeView.swift

https://github.com/user-attachments/assets/fc73f60c-a8a5-415e-8e0f-218dccbdebe8

Adding Add Comment View and demo button

---

Gauge/Profiles+Search/Views/ProfileView.swift
Gauge/Profiles+Search/Views/TakesView.swift

added missing environment object

added missing environment object

---

Gauge/Games/TakeMaster/Views/TakeMasterView.swift

"safe area fix for take master"

Games main

---

Gauge/Profiles+Search/ViewModels/ProfileViewModel.swift
Gauge/Profiles+Search/Views/FavoriteCard.swift
Gauge/Profiles+Search/Views/TakesView.swift
Gauge/Profiles+Search/Views/VoteCard.swift
Gauge/Profiles+Search/Views/VotesTabView.swift

Fixed tabs UI
